# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: detect-secrets
        name: Secret detection
        entry: uv run detect-secrets-hook
        language: system
        files: .*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
        args: [ --diff ]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.8
    hooks:
      - id: uv-lock
        args: ["--locked"]
        name: Check uv lockfile is in sync
      - id: uv-export
  {% if use_jupyter_notebooks and strip_jupyter_outputs %}
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  {% endif %}
