[tool.poetry]
name = "{{ distribution_name }}"
version = "{{ version }}"
description = "{{ project_short_description }}"
authors = [
  "{{ author_name }} <{{ author_email }}>"
]
license = "{{ license }}"
packages = [{include = "{{ package_name | replace('.', _copier_conf.sep) }}", from = "src"}]

[tool.poetry.dependencies]
python = "^{{ python_version }}"
{% if package_type == "cli" %}
typer = "^0.13.0"
{% endif %}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
flake8 = "^6.1.0"
flake8-builtins = "^2.1.0"
pep8-naming = "^0.13.3"
{% if testing_framework == "pytest" %}
pytest-mock = "^3.11.1"
flake8-pytest-style = "^1.7.2"
{% endif %}
{% if use_flake8_strict_plugins %}
flake8-print = "^5.0.0"
flake8-eradicate = "^1.5.0"
flake8-bugbear = "^23.9.16"
flake8-annotations = "^3.0.1"
{% endif %}
{% if use_mypy %}
mypy = "^1.11.2"
{% endif %}
black = "^22.1.0"
isort = "^5.12.0"
pre-commit = "^3.4.0"
pydocstyle = "^6.3.0"
bump2version = "^1.0.1"
detect-secrets = "^1.4.0"
{% if generate_docs == "mkdocs" %}
mkdocstrings-python = "^1.10.8"
mkdocs-material = "^9.5.32"
mkdocs-gen-files = "^0.5.0"
mkdocs-literate-nav = "^0.6.1"
{% endif %}
{% if generate_docs == "pdoc" %}
pdoc = "^14.6"
{% endif %}
{% if use_jupyter_notebooks %}
ipykernel = "^6.29.4"
nbdime = "^4.0.1"

[tool.poetry.group.jupyterlab]
optional = true
dependencies = { jupyterlab = "^4.2.2"}
{% endif %}

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"
{% if package_type == "cli" %}

[tool.poetry.scripts]
{{ package_name.split('.')[-1] }} = "{{ package_name }}.cli:app"
{% endif %}

[tool.black]
line-length = {{ max_line_length }}

[tool.isort]
profile = "black"

[tool.pydocstyle]
add_ignore = "D100,D103,D104"
convention = "google"

[tool.pytest.ini_options]
pythonpath = "src"

{% if use_mypy %}
[tool.mypy]
plugins = [
  "pydantic.mypy"
]
exclude = ["tests/*"]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
{% endif %}
